/*
 * prog2c/prog2c.c — Convert syscall trace to standalone C program.
 *
 * Like syzkaller's syz-prog2c: generates a C file that replays syscalls
 * directly via syscall(). The generated program can be compiled and
 * executed to trigger the same kernel paths.
 */
#define _GNU_SOURCE
#include "prog2c.h"
#include "../syscall/decode.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sched.h>
#include <libgen.h>
#include <sys/wait.h>
#include <sys/syscall.h>

/* ─── Generate C source from trace ────────────────────────────────────────── */

int prog2c_generate(struct sc_record *trace, int ntrace, const char *output_path)
{
	FILE *f = fopen(output_path, "w");
	if (!f) return -1;

	fprintf(f,
		"// Generated by vock prog2c\n"
		"#define _GNU_SOURCE\n"
		"#include <unistd.h>\n"
		"#include <sys/syscall.h>\n"
		"#include <sys/mman.h>\n"
		"#include <fcntl.h>\n"
		"#include <sched.h>\n"
#include <libgen.h>
		"#include <signal.h>\n"
		"#include <string.h>\n"
		"#include <stdio.h>\n"
		"#include <stdlib.h>\n"
		"#include <sys/socket.h>\n"
		"#include <sys/ioctl.h>\n"
		"#include <net/if.h>\n"
		"#include <linux/rtnetlink.h>\n"
		"\n"
		"int main(void)\n"
		"{\n"
		"\tlong r;\n"
		"\t(void)r;\n\n"
	);

	for (int i = 0; i < ntrace; i++) {
		const char *name = vock_syscall_name(trace[i].nr);
		fprintf(f, "\t// %s\n", name ? name : "unknown");
		fprintf(f, "\tr = syscall(%ldL", trace[i].nr);
		for (int a = 0; a < 6; a++)
			fprintf(f, ", 0x%lxUL", (unsigned long)trace[i].args[a]);
		fprintf(f, ");\n");
	}

	fprintf(f,
		"\n\treturn 0;\n"
		"}\n"
	);

	fclose(f);
	return 0;
}

/* ─── Compile ─────────────────────────────────────────────────────────────── */

int prog2c_compile(const char *src_path, const char *bin_path)
{
	char cmd[512];
	snprintf(cmd, sizeof(cmd),
		 "cc -w -O0 -o %s %s -static 2>/dev/null || "
		 "cc -w -O0 -o %s %s 2>/dev/null",
		 bin_path, src_path, bin_path, src_path);
	return system(cmd);
}

/* ─── Direct execution: fork + syscall() ──────────────────────────────────── */

int prog2c_exec(struct sc_record *trace, int ntrace)
{
	int status;
	pid_t pid;

	pid = fork();
	if (pid == 0) {
		unshare(CLONE_NEWUSER | CLONE_NEWNET | CLONE_NEWPID);
		for (int i = 0; i < ntrace; i++) {
			syscall(trace[i].nr,
				trace[i].args[0], trace[i].args[1],
				trace[i].args[2], trace[i].args[3],
				trace[i].args[4], trace[i].args[5]);
		}
		_exit(0);
	}
	if (pid < 0) return -1;

	waitpid(pid, &status, 0);
	return WIFEXITED(status) ? WEXITSTATUS(status) : -1;
}

/* ─── KCOV mode: compile + exec with LD_PRELOAD ──────────────────────────── */

int prog2c_exec_kcov(struct sc_record *trace, int ntrace)
{
	char src[64], bin[64], preload[512], exe[256];
	int status;
	pid_t pid;

	snprintf(src, sizeof(src), "/tmp/vock_%d.c", getpid());
	snprintf(bin, sizeof(bin), "/tmp/vock_%d", getpid());

	if (prog2c_generate(trace, ntrace, src) < 0)
		return -1;
	char cmd[512];
	snprintf(cmd, sizeof(cmd), "cc -w -O0 -o %s %s 2>/dev/null", bin, src);
	if (system(cmd) != 0) {
		unlink(src);
		return -1;
	}

	/* Find kcov.so relative to our binary */
	ssize_t n = readlink("/proc/self/exe", exe, sizeof(exe) - 1);
	if (n > 0) {
		exe[n] = '\0';
		char *dir = dirname(exe);
		snprintf(preload, sizeof(preload), "%s/mode/kcov.so", dir);
	} else {
		snprintf(preload, sizeof(preload), "./mode/kcov.so");
	}

	pid = fork();
	if (pid == 0) {
		setenv("LD_PRELOAD", preload, 1);
		execl(bin, bin, NULL);
		_exit(127);
	}
	if (pid < 0) { unlink(src); unlink(bin); return -1; }

	waitpid(pid, &status, 0);
	unlink(src);
	unlink(bin);
	return WIFEXITED(status) ? WEXITSTATUS(status) : -1;
}
