//! trace.syz → standalone C reproducer (port of prog2c/prog2c.c + the prog2c
//! subcommand parsing in vock.c).

use crate::syscall::{syscall_name, syscall_nr, Syscall};
use std::io::Write;

/// Generate a C program that replays `trace` via raw `syscall()`.
pub fn generate(trace: &[Syscall], output_path: &str) -> std::io::Result<()> {
    let mut f = std::fs::File::create(output_path)?;
    f.write_all(
        b"// Generated by vock prog2c\n\
#define _GNU_SOURCE\n\
#include <unistd.h>\n\
#include <sys/syscall.h>\n\
#include <sys/mman.h>\n\
#include <fcntl.h>\n\
#include <sched.h>\n\
#include <signal.h>\n\
#include <string.h>\n\
#include <stdio.h>\n\
#include <stdlib.h>\n\
#include <sys/socket.h>\n\
#include <sys/ioctl.h>\n\
#include <net/if.h>\n\
#include <linux/rtnetlink.h>\n\
\n\
int main(void)\n\
{\n\
\tlong r;\n\
\t(void)r;\n\n",
    )?;

    for sc in trace {
        let name = syscall_name(sc.nr).unwrap_or("unknown");
        write!(f, "\t// {name}\n")?;
        write!(f, "\tr = syscall({}L", sc.nr)?;
        for a in &sc.args {
            write!(f, ", 0x{:x}UL", *a as u64)?;
        }
        write!(f, ");\n")?;
    }

    f.write_all(b"\n\treturn 0;\n}\n")?;
    Ok(())
}

/// `vock prog2c <trace.syz> [-o output.c]`.
pub fn cmd(syz_file: &str, out_file: &str) -> i32 {
    let data = match std::fs::read_to_string(syz_file) {
        Ok(d) => d,
        Err(e) => {
            eprintln!("{syz_file}: {e}");
            return 1;
        }
    };

    let mut traces: Vec<Syscall> = Vec::new();
    for line in data.lines() {
        if traces.len() >= 4096 {
            break;
        }
        if line.starts_with('#') {
            continue;
        }
        let Some(paren) = line.find('(') else { continue };
        let name = &line[..paren];
        let Some(nr) = syscall_nr(name) else { continue };

        let mut args = [0i64; 6];
        let rest = &line[paren + 1..];
        let mut p = rest;
        for a in args.iter_mut() {
            let (val, next) = parse_leading_long(p);
            *a = val;
            p = next.trim_start_matches([',', ' ']);
            if p.is_empty() {
                break;
            }
        }
        let ret = line
            .find(") = ")
            .map(|i| parse_leading_long(&line[i + 4..]).0)
            .unwrap_or(0);

        traces.push(Syscall { nr, args, ret });
    }

    match generate(&traces, out_file) {
        Ok(()) => eprintln!("[prog2c] Generated {out_file} ({} syscalls)", traces.len()),
        Err(_) => eprintln!("[prog2c] Failed"),
    }
    0
}

/// Parse a leading integer like C's strtol(p, &end, 0): supports 0x hex,
/// leading sign, and stops at the first non-digit. Returns (value, remainder).
pub fn parse_leading_long(s: &str) -> (i64, &str) {
    let t = s.trim_start();
    let bytes = t.as_bytes();
    let mut i = 0;
    let neg = if i < bytes.len() && (bytes[i] == b'-' || bytes[i] == b'+') {
        let n = bytes[i] == b'-';
        i += 1;
        n
    } else {
        false
    };
    let (radix, start) = if t[i..].starts_with("0x") || t[i..].starts_with("0X") {
        (16, i + 2)
    } else {
        (10, i)
    };
    let mut end = start;
    while end < bytes.len() && (bytes[end] as char).is_digit(radix) {
        end += 1;
    }
    if end == start {
        return (0, s);
    }
    let mag = i64::from_str_radix(&t[start..end], radix).unwrap_or(0);
    (if neg { -mag } else { mag }, &t[end..])
}
